### ISSUE TITLE
Fruitphone should only disable Waila on first launch.

### ISSUE THREAD

**Issue by adegarimore** [elytra/FruitPhone#10]
FruitPhone-1.10.2-0.1.6
Forge build 2254

Some users of  unabridged might want to not use fruitphone. Why would they want that? I'm not sure. If you enable the visibility of Waila/Hwyla and restart the client, Waila/Hwyla is hidden again.

**Comment by exaskye** [comment]
The current solution to this is to disable "overwriteWaila" in the Fruit Phone config.

**Comment by adegarimore** [comment]
That works for now. Thanks 👍

**Comment by exaskye** [comment]
Keep in mind that will disable Fruit Phone's Waila integration entirely. That's a config change for whoever wants to enable Waila to make, not to be distributed with the pack by default.

**Comment by exaskye** [comment]
Possibility: Split overwriteWaila into overwriteWaila and showWailaInformation. The former would forcefully disable Waila,  the latter would just show Waila information in Fruit Phone.

Fruit Phone would ship with both on, but a modpack could ship with Waila pre-disabled and overwriteWaila disabled.

**Comment by adegarimore** [comment]
I feel like that would make the most sense.

**Comment by exaskye** [comment]
Fix published as [v0.1.7 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.7), [v0.1.7 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.7), and [v0.1.7 (1.7.10)](https://github.com/elytra/FruitPhone/releases/tag/1.7.10-0.1.7).
