### ISSUE TITLE
Add option to disable renering glasses on players

### ISSUE THREAD

**Issue by adegarimore** [elytra/FruitPhone#11]
FruitPhone-1.10.2-0.1.6
Forge build 2254

Some players might not want to see everyone wearing glasses

**Comment by exaskye** [comment]
Is the alwaysOn gamerule not enough?

**Comment by adegarimore** [comment]
I'm not familiar with that. I'll have to look into it tomorrow. I can always just wait to see if anyone complains about it.

**Comment by adegarimore** [comment]
alwaysOn will work. How about just adding a pair of invisible glasses? That seems like the simple and intuitive way of doing it.

**Comment by exaskye** [comment]
I believe invisible glasses are called contacts. And sure.

**Comment by exaskye** [comment]
Fix published as [v0.1.7 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.7), [v0.1.7 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.7), and [v0.1.7 (1.7.10)](https://github.com/elytra/FruitPhone/releases/tag/1.7.10-0.1.7).
