### ISSUE TITLE
Glasses fall off when going through Nether portal 

### ISSUE THREAD

**Issue by a-frenzy** [elytra/FruitPhone#12]
Fruitphone 0.1.5, MC1.10.2, Forge 12.18.3.2239

No log, the glasses seem to fall off or stop working after going through a nether portal with only fruitphone/probedataproviderapi installed, should be reproducible. Putting another set of glasses on will fix it and make the old set drop in your inventory. Not sure if bug or feature

**Comment by exaskye** [comment]
Must be the dimensional winds from going through the portal. I'll make the glasses more resistant.

**Comment by exaskye** [comment]
Fix published as [v0.1.7 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.7), [v0.1.7 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.7), and [v0.1.7 (1.7.10)](https://github.com/elytra/FruitPhone/releases/tag/1.7.10-0.1.7).
