### ISSUE TITLE
Crash when looking at Forge Multipart blocks

### ISSUE THREAD

**Issue by Fortist** [elytra/FruitPhone#13]
- V1.7
- MC 1.7.10
- Forge 1614
CRASHLOG: http://pastebin.com/nau4kWhR

While just going around and looking at things I got this crash when I made it to a generator I had, Im thinking it happened with the "Iron Pipe" from Magneticraft.

Also, my suggestion is possibly the configuration option of the removal of the inventory slots when looking at things. But I think thats "The One Probe's" option, but that'd remove the bars, which I do want.

**Comment by exaskye** [comment]
What in fresh hell is this?

CODECHICKEN PLEASE STOP

**Comment by exaskye** [comment]
Experimental fix: https://unascribed.com/f/26f88d1f_FruitPhone-1.7.10-0.1.7-exp1.jar

Let me know if this works. It should make anything from a CodeChicken mod not show a tooltip, because I have no interest in going on a wild goose chase series of bug reports.

**Comment by Fortist** [comment]
It's working. No crashing yet.
However, all the Mekanism Pipes only show "Waila Error Waila Error" except the Energy pipe actually shows RF value and none of them show the Mod Id (Ergo "Mekanism")
Ender Storage tanks show that as well, but at least show the color code and amount of fluid stored, missing "Ender Storage" mod id however.

Some other things show "fruitphone.capError" like EnderIO energy conduits
