### ISSUE TITLE
"probedataprovider : any" not recognizing Hwyla 

### ISSUE THREAD

**Issue by rocode** [elytra/FruitPhone#17]
**FruitPhone:** 1.11.2-0.1.7
**Minecraft:** 1.11.2
**Forge:** 1.11.2-13.20.0.2294
**Hwyla:** 1.8.13-B26_1.11
![screenshot from 2017-05-02 18-23-37](https://cloud.githubusercontent.com/assets/265267/25644592/a685afac-2f64-11e7-86a6-4b55463265f5.png)

Trying to package FruitPhone for a modpack. I get this error with both Hwyla and FruitPhone in the "mods" folder.

**Comment by exaskye** [comment]
Fruit Phone *requires* ProbeDataProviderAPI. It simply cannot run without it, as the Hwyla shim converts Waila data to Probe data.

**Comment by rocode** [comment]
I realized my mistake as soon as I posted and returned back to the main github page. Damn your quickness, couldn't delete it in time! Thanks. :P
