### ISSUE TITLE
Crash when using Power Drill without glasses

### ISSUE THREAD

**Issue by heidrifx** [elytra/FruitPhone#3]
Title pretty much explains everything.
Crash: http://pastebin.com/M3VMg4DH

**Comment by exaskye** [comment]
This works fine in 1.11.2 ;_;

Stupid null itemstacks!

**Comment by exaskye** [comment]
Fix published as [v0.1.5](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.5).
