### ISSUE TITLE
Crashes involving entities

### ISSUE THREAD

**Issue by a-frenzy** [elytra/FruitPhone#4]
Fruitphone 0.1.3, Forge 12.18.3.2239, Minecraft 1.10.2

Two crashlogs here https://gist.github.com/frenzye/5ddd457951bb0938741413b779b820ed
and another one https://gist.github.com/frenzye/0c4733040d14124970ec95959e9ed1c1

**Comment by darkevilmac** [comment]
@unascribed To save you some time, you're referencing Minecraft.getMinecraft here with no side checks. https://github.com/elytra/FruitPhone/blob/1.11.2/src/main/java/com/elytradev/fruitphone/FruitPhone.java#L439-L448

**Comment by exaskye** [comment]
...How the hell did I mess this up?

**Comment by exaskye** [comment]
Fix pushed as [v0.1.4 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.4) and [v0.1.3 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.3)

**Comment by a-frenzy** [comment]
This mod is smart as hell and you have my thanks for a quick fix
