### ISSUE TITLE
Client crash when looking at Not Enough Wand's Illumination Wand sphere

### ISSUE THREAD

**Issue by a-frenzy** [elytra/FruitPhone#5]
Fruitphone 0.1.4, Forge 12.18.3.2239, Minecraft 1.10.2

Not sure if this is on Not Enough Wands, will report there if so 

Crashlogs: https://gist.github.com/frenzye/1dd557405bc04056f4fb1547b0f9f0e0
https://gist.github.com/frenzye/888366ead4aac78e763278011dffd9ee

**Comment by exaskye** [comment]
Nope, this is me being an idiot.

**Comment by exaskye** [comment]
(Actually doesn't affect 1.11.2 because it's a NULL ITEMSTAAAACK SHDG HL:DGJ:GD )

**Comment by exaskye** [comment]
Fix published as [v0.1.5](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.5).
