### ISSUE TITLE
Loading Animation on Block Icons

### ISSUE THREAD

**Issue by nicksloan11** [elytra/FruitPhone#9]
I'm getting a loading animation over the blocks. Is that because I'm only using the client mod?

![2](https://cloud.githubusercontent.com/assets/2148822/23637679/b3bdb9c4-02a2-11e7-8723-270b4470d312.jpg)
![1](https://cloud.githubusercontent.com/assets/2148822/23637680/b3cb1e34-02a2-11e7-889e-291ccb87b0e1.jpg)

Mod Version: v0.1.6 (1.7.10)
Minecraft Version: 1.7.10
Forge Version: 10.13.4.1614

**Comment by exaskye** [comment]
Since you're only using it on the client, this makes sense, but it's not how it's supposed to work, so... bug.

**Comment by exaskye** [comment]
I should probably leverage Waila's NBT sync packets instead of using my own, so that you can use Fruit Phone on the client and Waila on the server.

**Comment by exaskye** [comment]
Fix published as [v0.1.7 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.7), [v0.1.7 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.7), and [v0.1.7 (1.7.10)](https://github.com/elytra/FruitPhone/releases/tag/1.7.10-0.1.7).
